baseurl = "https://rabbithole223.com/"
DefaultContentLanguage = "en"
title = "Rabbit Hole 223"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Knowledge Through Errors" # Set a different text for the header on the home page
  subtitle = "Knowledge by Errors"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employerâ€™s view in any way."


[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "RH223"
  website = "https://www.rabbithole223.com/"
  email = "spam@rabbithole223.com"
  github = "rabbithole223"
  twitter = "rabbithole223"
  reddit = "rabbithole223"
  linkedin = "rabbithole223"
  youtube = "channel/rabbithole2237" # or channel/channelname
  rumble = "c/c-rabbithole223"
  printables = "https://www.printables.com/rabbithole223"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = ""
    weight = 2

# [[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
