blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/fitsnips/web-rabbithole223.com/discussions
    about: Ask questions about the blog or mushroom cultivation
